---
title: "installing software"
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
opts_chunk$set(collapse = TRUE, comment = "#>")
opts_chunk$set(warning = TRUE, message = TRUE) 
knit_hooks$set(inline = function(x) {
	if (!is.numeric(x)) { 
		x 
		} else if (x >= 10000) { 
		prettyNum(round(x, 2), big.mark = ",")
		} else {
		prettyNum(round(x, 2))
		}
	})
```

Before we can collaborate GitHub for version control, both you and your collaborator have to install software and setup accounts as follows. 


## install R and RStudio

Both you and your collaborator install R and RStudio on your local machines. If you already have R and RStudio installed, please update to the most recent releases and update your R packages as well.

Windows users may have to login as an Administrator before installing the software. 

- [Install R](https://cloud.r-project.org){target="_blank"} for your operating system  
- [Install RStudio](https://www.rstudio.com/products/rstudio/#Desktop){target="_blank"}, a user interface for R  

## install git

Both you and your collaborator install git on your local machines. Once installed, we access its functionality via the RStudio interface. 

Jenny Bryan provided these installation instructions for a workshop I attended. I suggest you read all the instructions before starting.

- [Git already
    installed?](https://happygitwithr.com/install-git.html#git-already-installed)
- [Windows](https://happygitwithr.com/install-git.html#install-git-windows)
    install
- [Mac OS](https://happygitwithr.com/install-git.html#macos) install
- [Linux](https://happygitwithr.com/install-git.html#linux) install

Optional reading: Read sections 1 and 2 of [Excuse me, do you have a moment to talk about version control?](https://dx.doi.org/10.7287%2Fpeerj.preprints.3159v2) for a good introduction to version control.

## setup GitHub

Both you and you collaborator need an account with GitHub. 

GitHub is a hosting service that provides an online home for your
Git-based projects—critically important for sharing with collaborators.
Once you have a GitHub account, you will update your repositories using
the RStudio interface.

- [Join GitHub Education](https://education.github.com/students) —
    it’s free.

Once you have a GitHub account, do the following steps. I suggest you read the full instructions for a step before doing that step.

- Some instructions ask you to type commands in the “shell”. To access the shell, open RStudio and use the pulldown menu *Tools \> Shell*.
- [Introduce yourself to Git](http://happygitwithr.com/hello-git.html#hello-git) using the name and email you used with your GitHub account
- [Cache your username and password](http://happygitwithr.com/credential-caching.html#credential-caching) or so you don’t need to authenticate yourself to GitHub interactively ad nauseum. Alternatively, you can [set up SSH keys](http://happygitwithr.com/ssh-keys.html#ssh-keys).
- [Prove RStudio can find local Git](http://happygitwithr.com/rstudio-git-github.html#rstudio-git-github) and, therefore, can talk to GitHub

Cleanup

  - Close the Shell window
  - Delete the test project on your machine
  - Delete the test repo on GitHub, *Settings \> Danger Zone \> Delete
    this repository*

