---
title: "collaboration among project administrators"
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
opts_chunk$set(collapse = TRUE, comment = "#>")
opts_chunk$set(warning = TRUE, message = TRUE) 
knit_hooks$set(inline = function(x) {
	if (!is.numeric(x)) { 
		x 
		} else if (x >= 10000) { 
		prettyNum(round(x, 2), big.mark = ",")
		} else {
		prettyNum(round(x, 2))
		}
	})
```

To proceed, the **author** has a project in a GitHub repo and wants to invite a **collaborator**. 

Both author and collaborator have completed the [Installing software](p001-install-software.md) instructions. 

In this approach, the collaborator has authority to edit the project material without pre-approval by other administrators. 

The repo author: 

- Make the repo public or private 
- Obtain the collaborator's GitHub name or email address associated with their GitHub account 
- Navigate to the project repo on GitHub 
- Click on the *Settings* icon 
- Click on the *Manage access* tab 
- Click on the *Invite teams or people* button 
- Type the collaborator's GitHub name or email in the dialog box. 

The collaborator: 

- Receives the invitation and accepts the invitation 




***
<a href="#top">&#9650; top of page</a>    
[&#9665; main page](../README.md)
