---
title: "initiating a collaboration"
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(knitr)
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
opts_chunk$set(collapse = TRUE, comment = "#>")
opts_chunk$set(warning = TRUE, message = TRUE) 
knit_hooks$set(inline = function(x) {
	if (!is.numeric(x)) { 
		x 
		} else if (x >= 10000) { 
		prettyNum(round(x, 2), big.mark = ",")
		} else {
		prettyNum(round(x, 2))
		}
	})
```

We'll assume that you (the **author**) have a project in a GitHub repo and that you want to invite a **collaborator**. Both the author and the collaborator should have completed the [Installing software](p001-install-software.md) instructions. 

There are two approaches: 

1. The collaborator is one of the project administrators. For example, in MIDFIELD, the administrator team includes Ohland, Lord, Long, Orr, and Layton. 
2. The collaborator is not an administrator so their work has to be reviewed by one of the administrators before being accepted. Grad students might fall into this category. 




## collaboration among project administrators

In this approach, the collaborator has authority to edit the project material without pre-approval by other administrators. 

The repo author: 

- The repo can be public or private
- You need your collaborator's GitHub name or email address associated with their GitHub account 
- Navigate to your project repo on GitHub 
- Click on the *Settings* icon 
- Click on the *Manage access* tab 
- Click on the *Invite teams or people* button 
- Type the collaborator's GitHub name or email in the dialog box. 

The collaborator: 

- Receives the invitation and accepts the invitation 







## collaboration that requires admin review

The repo author: 

- The repo has to be public for the collaborator to be able to fork it. 
- Give the repo URL to the collaborator

The collaborator: 

- Navigates to the repo
- Click the *Fork* button and select the destination (typically your GitHub account) 
